export const products = [
    {
      id: "1",
      title: "Playstation 5",
      price: 1200000,
      stock: 20,
      category: "Consolas",
      description: "La consola de última generación de Sony, diseñada para ofrecer una experiencia de gaming inmersiva con gráficos de alta calidad, velocidad ultrarrápida y juegos exclusivos.",
      imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862316/840638_y0hlju.jpg",
    },
    {
        id: "2",
        title: "XBOX Series S",
        price: 900000,
        stock: 40,
        category: "Consolas",
        description: "La consola compacta de Microsoft con tecnología de próxima generación, ofreciendo velocidad, gráficos impresionantes y compatibilidad con una amplia biblioteca de juegos.",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862421/FW7GLBVXPRKNXBV63ZSAGRGGYI_sxh1ho.jpg",
      },
      {
        id: "3",
        title: "Teclado Redragon Kumara",
        price: 55000,
        stock: 200,
        category: "Perifericos",
        description: "Teclado mecánico compacto con interruptores robustos, retroiluminación RGB y teclas resistentes, ideal para jugadores que buscan un alto rendimiento y durabilidad.",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862509/large_86fnSdyGW7MswKp73sx2XvduPPbwZzJlqUogluDX_d3ifwb.png",
      },
      {
        id: "4",
        title: "Mouse Logitech Series Hero",
        price: 68000,
        stock: 350,
        category: "Perifericos",
        description: "Mouse ergonómico con sensores de alta precisión, diseño personalizable y una experiencia de juego fluida y precisa, ideal para gamers profesionales.",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862580/mouse-inalambrico-gamer-logitech-g502-lightspeed-g-series-16000dpi-rgb-84fd0f1720cdaf9c7b17092321983499-1024-1024_b7tu7x.jpg",
      },
      {
        id: "5",
        title: "Placa de video MSI Ventus Trio RTX 4070",
        price: 850000,
        stock: 40,
        category: "PC",
        description: "Placa gráfica de alto rendimiento con arquitectura NVIDIA Ampere, soporte para ray tracing y DLSS, ideal para juegos en 4K y tareas de edición gráfica.",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862691/msi_geforce_rtx_4070_super_ventus_3x_12gb_gddr6x_oc1_vkqwrf.jpg",
      },
      {
        id: "6",
        title: "Microprocesador Intel Core i7",
        price: 400000,
        stock: 65,
        category: "PC",
        description: "Procesador de alto rendimiento de Intel, con múltiples núcleos y subprocesos, diseñado para ofrecer velocidad y eficiencia en juegos, creación de contenido y multitarea.",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862757/microprocesador-intel-core-i7-10700-cometlake-s1200-box_zvappt.jpg",
      },
      {
        id: "7",
        title: "Laptop Lenovo i7, 16gb Ram, 512gb SSD",
        price: 1439999,
        stock: 10,
        category: "Notebooks",
        description: "Laptop potente y versátil con procesador Intel i7, 16GB de RAM y almacenamiento rápido en SSD, ideal para productividad, entretenimiento y trabajo multitarea.",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1739316423/D_NQ_NP_777288-MLA80405333798_112024-O_h6wscp.webp",
      },
      {
        id: "8",
        title: "Notebook Asus Vivobook 16 X1605",
        price: 1749999,
        stock: 7,
        category: "Notebooks",
        description: "Notebook ligera con pantalla Full HD de 16, procesador eficiente y batería de larga duración, perfecta para estudiantes y profesionales en movimiento.",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1739316450/D_NQ_NP_762609-MLA79880312743_102024-O_kmsep8.webp",
      },
  ];