export const products = [
    {
      id: "1",
      title: "Playstation 5",
      price: 1200000,
      stock: 20,
      category: "Consolas",
      description: "Última consola de Sony, la Playstation 5",
      imageUrl: "",
    },
    {
        id: "2",
        title: "XBOX Series S",
        price: 900000,
        stock: 40,
        category: "Consolas",
        description: "Última consola de Microsoft, la XBOX Series S",
        imageUrl: "",
      },
      {
        id: "3",
        title: "Teclado Redragon Kumara",
        price: 55000,
        stock: 200,
        category: "Accesorios",
        description: "Teclado gamer Redragon Kumara el mejor",
        imageUrl: "",
      },
      {
        id: "4",
        title: "Mouse Logitech Series Hero",
        price: 68000,
        stock: 350,
        category: "Accesorios",
        description: "Mouse Logitech Series Hero el mejor mouse",
        imageUrl: "",
      },
      {
        id: "5",
        title: "Placa de video MSI RTX 3060",
        price: 850000,
        stock: 40,
        category: "Pc",
        description: "La mejor placa del mercado",
        imageUrl: "",
      },
      {
        id: "6",
        title: "Procesador Intel Core i7",
        price: 400000,
        stock: 65,
        category: "Pc",
        description: "El mejor procesador gamer",
        imageUrl: "",
      },
  ];