export const products = [
    {
      id: "1",
      title: "Playstation 5",
      price: 1200000,
      stock: 20,
      category: "Consolas",
      description: "Última consola de Sony, la Playstation 5",
      imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862316/840638_y0hlju.jpg",
    },
    {
        id: "2",
        title: "XBOX Series S",
        price: 900000,
        stock: 40,
        category: "Consolas",
        description: "Última consola de Microsoft, la XBOX Series S",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862421/FW7GLBVXPRKNXBV63ZSAGRGGYI_sxh1ho.jpg",
      },
      {
        id: "3",
        title: "Teclado Redragon Kumara",
        price: 55000,
        stock: 200,
        category: "Accesorios",
        description: "Teclado gamer Redragon Kumara el mejor",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862509/large_86fnSdyGW7MswKp73sx2XvduPPbwZzJlqUogluDX_d3ifwb.png",
      },
      {
        id: "4",
        title: "Mouse Logitech Series Hero",
        price: 68000,
        stock: 350,
        category: "Accesorios",
        description: "Mouse Logitech Series Hero el mejor mouse",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862580/mouse-inalambrico-gamer-logitech-g502-lightspeed-g-series-16000dpi-rgb-84fd0f1720cdaf9c7b17092321983499-1024-1024_b7tu7x.jpg",
      },
      {
        id: "5",
        title: "Placa de video MSI Ventus Trio RTX 4070",
        price: 850000,
        stock: 40,
        category: "Pc",
        description: "La mejor placa del mercado",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862691/msi_geforce_rtx_4070_super_ventus_3x_12gb_gddr6x_oc1_vkqwrf.jpg",
      },
      {
        id: "6",
        title: "Microprocesador Intel Core i7",
        price: 400000,
        stock: 65,
        category: "Pc",
        description: "El mejor procesador gamer",
        imageUrl: "https://res.cloudinary.com/dhwsxp2c8/image/upload/v1738862757/microprocesador-intel-core-i7-10700-cometlake-s1200-box_zvappt.jpg",
      },
  ];